# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_mkdocs_tutorial_2024',
                'doc_host': 'https://harishmohanraj.github.io',
                'git_url': 'https://github.com/harishmohanraj/nbdev_mkdocs_tutorial_2024',
                'lib_path': 'nbdev_mkdocs_tutorial_2024'},
  'syms': { 'nbdev_mkdocs_tutorial_2024.core': { 'nbdev_mkdocs_tutorial_2024.core.foo': ( 'core.html#foo',
                                                                                          'nbdev_mkdocs_tutorial_2024/core.py')}}}
